[package]
name = "SafeBet"
version = "1.0.0"
authors = ["SafeBet Team"]

[addresses]
safebet = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

# Uncomment when integrating with Aave
# [dependencies.Aave]
# git = "https://github.com/aave/aptos-aave-v3.git"
# rev = "main"
# subdir = "aave-pool"

[dev-dependencies]
